/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import dominio.Cita;
import java.util.Calendar;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import negocio.IFacadadeNegocio;
import constantes.Constantes;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class PantallaCitas extends javax.swing.JDialog {
    private int ESPACIO_ENTRE_LINEAS = 40;
    private IFacadadeNegocio facadadeNegocio;
    private List<Cita> listaDeCitas;
    private Calendar fechaActual;
    //private Calendar fechaActual2;
    /**
     * Creates new form PantallaCitas
     * @param parent
     * @param modal
     * @param facadadeNegocio
     */
    public PantallaCitas(java.awt.Frame parent, boolean modal, IFacadadeNegocio facadadeNegocio) {
        super(parent, modal);
        initComponents();
        this.facadadeNegocio = facadadeNegocio;
        this.fechaActual = Calendar.getInstance();
        fechaActual.add(Calendar.DATE,-1);
        //fechaActual2 = Calendar.getInstance();
        this.jLabel_Fecha.setText(facadadeNegocio.formatearFecha(fechaActual.getTime()));
        this.setLocationRelativeTo(null);
    }
    
    public void cargarCitas() {
        this.listaDeCitas = facadadeNegocio.obtenerCitasPorFecha(fechaActual.getTime());
        String nombreColumnas [] = {"Fecha","Hora","Nombre","Servicio","Precio"};
        String cita[][]= new String[this.listaDeCitas.size()][5];
        Cita citaAuxiliar;
        int saltosdeLinea = 1;
        for (int i = 0; i < this.listaDeCitas.size(); i++) {
            citaAuxiliar = this.listaDeCitas.get(i);
            cita[i][0] = this.facadadeNegocio.formatearFecha(citaAuxiliar.getFecha());
            cita[i][1] = this.facadadeNegocio.formatearHora(citaAuxiliar.getHora());
            cita[i][2] = citaAuxiliar.getIdCliente().getNombre() + " " + 
                    citaAuxiliar.getIdCliente().getApellido();
            cita[i][3] = citaAuxiliar.getServicios();
            System.out.println("Prueba");
            System.out.println(citaAuxiliar.getServicioderelajacionList().size());
            cita[i][4] = citaAuxiliar.getCostoTotal().toString();
            if (saltosdeLinea > cita[i][3].split("<br>").length) {
                saltosdeLinea = cita[i][3].split("<br>").length;
            }
        }
        jTable_Citas.setRowHeight(saltosdeLinea*this.ESPACIO_ENTRE_LINEAS);
        
        this.jTable_Citas.setModel(new DefaultTableModel(cita, nombreColumnas));
    }
    
    public void cambiarFecha(int movimiento) {
        this.fechaActual.add(Calendar.DATE, movimiento);
        //this.fechaActual2.add(Calendar.DATE, movimiento);
        this.jLabel_Fecha.setText(facadadeNegocio.formatearFecha(fechaActual.getTime()));
        this.cargarCitas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Citas = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jPanel1 = new javax.swing.JPanel();
        jLabel_Fecha = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton_AgregarCita = new javax.swing.JButton();
        jButton_ModificarCita = new javax.swing.JButton();
        jButton_EliminarCita = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable_Citas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable_Citas);

        jLabel_Fecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Fecha");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton1.setText("<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(">");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton_AgregarCita.setText("Agregar Cita");
        jButton_AgregarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AgregarCitaActionPerformed(evt);
            }
        });

        jButton_ModificarCita.setText("Modificar Cita");
        jButton_ModificarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ModificarCitaActionPerformed(evt);
            }
        });

        jButton_EliminarCita.setText("Eliminar Cita");
        jButton_EliminarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EliminarCitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_EliminarCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_ModificarCita, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(jButton_AgregarCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton2)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addComponent(jButton_AgregarCita)
                .addGap(18, 18, 18)
                .addComponent(jButton_ModificarCita)
                .addGap(18, 18, 18)
                .addComponent(jButton_EliminarCita)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.cambiarFecha(1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.cambiarFecha(-1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_AgregarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AgregarCitaActionPerformed
        this.mostrarPantallaCita(Constantes.AGREGAR, null);
    }//GEN-LAST:event_jButton_AgregarCitaActionPerformed

    private void jButton_ModificarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ModificarCitaActionPerformed
        this.mostrarPantallaCita(Constantes.MODIFICAR, null);
    }//GEN-LAST:event_jButton_ModificarCitaActionPerformed

    private void jButton_EliminarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EliminarCitaActionPerformed
        this.mostrarPantallaCita(Constantes.ELIMINAR, null);
    }//GEN-LAST:event_jButton_EliminarCitaActionPerformed

    public void mostrarPantallaCita(int tipoDeOperacion, Cita cita) {
        PantallaCita pantallaCita = PantallaCita.getInstancia(null, true, this.facadadeNegocio);
        this.setVisible(false);
        if(tipoDeOperacion == Constantes.AGREGAR) {
            pantallaCita.mostrarPantalla(tipoDeOperacion, cita);
        } else {
            int fila = this.jTable_Citas.getSelectedRow();
            if (fila != -1) {
                Cita citaSeleccion = this.listaDeCitas.get(fila);
                pantallaCita.mostrarPantalla(tipoDeOperacion, citaSeleccion);
            } else {
                this.mostrarAdvertencia("Seleccione una cita", JOptionPane.ERROR_MESSAGE);
            }
        }
        this.cargarCitas();
        this.setVisible(true);
    }
    
    public void mostrarAdvertencia(String mensaje, int tipoDeMensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Mensaje", tipoDeMensaje);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_AgregarCita;
    private javax.swing.JButton jButton_EliminarCita;
    private javax.swing.JButton jButton_ModificarCita;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Fecha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_Citas;
    // End of variables declaration//GEN-END:variables
}
