/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import constantes.Constantes;
import dominio.Cliente;
import java.util.List;
import negocio.IFacadadeNegocio;
import com.mxrck.autocompleter.*;
import dominio.Producto;
import dominio.Servicioderelajacion;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import negocio.ServicioDeRelajacionControl;

/**
 *
 * @author pc
 */
public class PantallaServicio extends javax.swing.JDialog{

    private static PantallaServicio pantallaServicio;
    private Servicioderelajacion servicio;
    private int operacion;
    private IFacadadeNegocio facadadeNegocio;
    //private Autocompletar autocompletar;
    /**
     * Creates new form PantallaCita
     */
    private PantallaServicio(java.awt.Frame parent, boolean modal, IFacadadeNegocio facadadeNegocio) {
        super(parent, modal);
        this.facadadeNegocio = facadadeNegocio;
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public static PantallaServicio getInstancia(java.awt.Frame parent, boolean modal,IFacadadeNegocio facadadeNegocio) {
        if(pantallaServicio == null) {
            pantallaServicio = new PantallaServicio(parent, modal, facadadeNegocio);
        }
        return pantallaServicio;
    }

    public void actualizarPantalla(int operacion, Servicioderelajacion servicio) {
        this.operacion = operacion;
        this.servicio = servicio;
        if(operacion == Constantes.AGREGAR) {
            this.jLabel_Titulo.setText("Agregar Servicio");
            this.jButton_GuardarCliente.setText("Guardar Servicio");
        } else if (operacion == Constantes.MODIFICAR) {
            this.jLabel_Titulo.setText("Actualizar Servicio");
            this.jButton_GuardarCliente.setText("Actualizar Servicio");
            
        } else if (operacion == Constantes.ELIMINAR) {
            this.jLabel_Titulo.setText("Eliminar Servicio");
            this.jButton_GuardarCliente.setText("Eliminar Servicio");
            this.setEditableComponentes(false);
        }
        
        if (operacion == Constantes.MODIFICAR || operacion == Constantes.ELIMINAR) {
            this.jTextField_Id.setText(Integer.toString(servicio.getIdServicioDeRelajacion()));
            this.jTextField1_Nombre.setText(servicio.getNombre());
            this.jSpinner1_hora.setValue(servicio.getDuracion().getHours());
            this.jSpinner1_Minuto.setValue(servicio.getDuracion().getMinutes());
            this.jSpinner1_costo.setValue(servicio.getCosto());
        }
        
        if(operacion == Constantes.MODIFICAR || operacion == Constantes.AGREGAR) {
            this.setEditableComponentes(true);
        }
    }
    
    public void setEditableComponentes(boolean bln){
        this.jTextField_Id.setEditable(false);
        this.jTextField1_Nombre.setEditable(bln);
        this.jSpinner1_hora.setEnabled(bln);
        this.jSpinner1_Minuto.setEnabled(bln);
        this.jSpinner1_costo.setEnabled(bln);
    }
    
    public void cerrarPantalla() {
        this.setVisible(false);     
    }
    
    public void limpiarPantalla() {
        this.jTextField_Id.setText("");
        this.jTextField1_Nombre.setText("");
        this.jSpinner1_hora.setValue(0);
        this.jSpinner1_Minuto.setValue(0);
        this.jSpinner1_costo.setValue(0);
    }
    
    public void mostrarPantalla(int operacion, Servicioderelajacion servicio) {
        this.limpiarPantalla();
        this.actualizarPantalla(operacion, servicio);
        this.setVisible(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Titulo = new javax.swing.JLabel();
        jPanel_DatosCita = new javax.swing.JPanel();
        jTextField_Id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1_Nombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSpinner1_hora = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jSpinner1_Minuto = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSpinner1_costo = new javax.swing.JSpinner();
        jButton_Cancelar = new javax.swing.JButton();
        jButton_GuardarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Titulo.setToolTipText("");

        jTextField_Id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_IdKeyPressed(evt);
            }
        });

        jLabel2.setText("ID:");

        jLabel8.setText("Nombre:");

        jTextField1_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_NombreActionPerformed(evt);
            }
        });

        jLabel9.setText("Duración:");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Costo:");

        jLabel1.setText("hr");

        jLabel3.setText("min");

        javax.swing.GroupLayout jPanel_DatosCitaLayout = new javax.swing.GroupLayout(jPanel_DatosCita);
        jPanel_DatosCita.setLayout(jPanel_DatosCitaLayout);
        jPanel_DatosCitaLayout.setHorizontalGroup(
            jPanel_DatosCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_DatosCitaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_DatosCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel_DatosCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_DatosCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField_Id, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                        .addGroup(jPanel_DatosCitaLayout.createSequentialGroup()
                            .addComponent(jSpinner1_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSpinner1_Minuto, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel3))
                        .addComponent(jTextField1_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                    .addComponent(jSpinner1_costo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_DatosCitaLayout.setVerticalGroup(
            jPanel_DatosCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DatosCitaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel_DatosCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_DatosCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField1_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_DatosCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jSpinner1_hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1_Minuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_DatosCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jSpinner1_costo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jButton_Cancelar.setText("Cancelar");
        jButton_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarActionPerformed(evt);
            }
        });

        jButton_GuardarCliente.setText("Guardar Cliente");
        jButton_GuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GuardarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton_Cancelar)
                                .addGap(63, 63, 63)
                                .addComponent(jButton_GuardarCliente)
                                .addGap(158, 158, 158))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel_DatosCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_DatosCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_GuardarCliente)
                    .addComponent(jButton_Cancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_GuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GuardarClienteActionPerformed
        //VALIDAR CAMPOS
        if (operacion == Constantes.AGREGAR) {
            if (this.validarCampos(Constantes.AGREGAR)) {
                if (this.mostrarMensajeDeConfirmacion("¿Desea guardar el servicio?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    this.servicio = new Servicioderelajacion();
                    this.servicio.setNombre(this.jTextField1_Nombre.getText());
                    this.servicio.setDuracion(this.facadadeNegocio.convertirHoras((int) this.jSpinner1_hora.getValue(), (int) this.jSpinner1_Minuto.getValue()));
                    this.servicio.setCosto((float)(int)this.jSpinner1_costo.getValue());
                    if (verificarServicio(servicio)) {
                        this.facadadeNegocio.agregarServicioDeRelajacion(servicio);
                        this.mostrarMensajeDeAdvertencia("Servicio guardado correctamente", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        this.mostrarMensajeDeAdvertencia("Ya existe un servicio con el mismo nombre", JOptionPane.INFORMATION_MESSAGE);
                        return;
                    }
                }
            } else {
                return;
            }
        } else if (operacion == Constantes.MODIFICAR) {
            if (this.validarCampos(Constantes.MODIFICAR)) {
                if (this.mostrarMensajeDeConfirmacion("¿Desea actualizar el servicio?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    this.servicio.setNombre(this.jTextField1_Nombre.getText());
                    this.servicio.setCosto((float)(int)this.jSpinner1_costo.getValue());
                    this.servicio.setDuracion(this.facadadeNegocio.convertirHoras((int) this.jSpinner1_hora.getValue(), (int) this.jSpinner1_Minuto.getValue()));
                    this.facadadeNegocio.actualizarServicioDeRelajacion(servicio);
                }
            } else {
                return;
            }
        } else if (this.operacion == Constantes.ELIMINAR) {
            if(this.mostrarMensajeDeConfirmacion("¿Desea eliminar el servicio?",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                this.facadadeNegocio.eliminarServicioDeRelajacion(this.servicio);
                this.mostrarMensajeDeAdvertencia("Servicio eliminado correctamente",JOptionPane.INFORMATION_MESSAGE);
            }
        }
//        
        this.cerrarPantalla();
    }//GEN-LAST:event_jButton_GuardarClienteActionPerformed

    private void jButton_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarActionPerformed
        this.cerrarPantalla();
    }//GEN-LAST:event_jButton_CancelarActionPerformed

    private void jTextField_IdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_IdKeyPressed
//        this.jTextField_Id.setText("0");
    }//GEN-LAST:event_jTextField_IdKeyPressed

    private void jTextField1_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_NombreActionPerformed

    public int mostrarMensajeDeConfirmacion(String mensaje,int tipoDeMensaje) {
        return JOptionPane.showConfirmDialog(this, mensaje, "Mensaje", tipoDeMensaje);
    }
    
    public void mostrarMensajeDeAdvertencia(String mensaje, int tipoDeMensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Mensaje", tipoDeMensaje);
    }
    
    public boolean validarCampos(int operacion) {
        if(this.jTextField1_Nombre.getText().equals("")) {
            mostrarMensajeDeAdvertencia("Ingrese un Nombre", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if((int)this.jSpinner1_hora.getValue()< 0) {
            mostrarMensajeDeAdvertencia("Ingrese una hora correcta", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if((int)this.jSpinner1_Minuto.getValue()< 0) {
            mostrarMensajeDeAdvertencia("Ingrese un minuto correcto", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if ((int)this.jSpinner1_costo.getValue()<=0) {
            mostrarMensajeDeAdvertencia("Ingrese un precio correcto", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;   
    }
    
    public boolean verificarServicio(Servicioderelajacion servicio){
        List<Servicioderelajacion> listServiciosAuxiliar = facadadeNegocio.obtenerServiciosDeRelajacion();
        for (Servicioderelajacion servicioAux : listServiciosAuxiliar) {
            if (servicioAux.getNombre()==(servicio.getNombre())) {
                return false;
            }
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cancelar;
    private javax.swing.JButton jButton_GuardarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JPanel jPanel_DatosCita;
    private javax.swing.JSpinner jSpinner1_Minuto;
    private javax.swing.JSpinner jSpinner1_costo;
    private javax.swing.JSpinner jSpinner1_hora;
    private javax.swing.JTextField jTextField1_Nombre;
    private javax.swing.JTextField jTextField_Id;
    // End of variables declaration//GEN-END:variables


}
