/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import dominio.Cita;
import java.util.Calendar;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import negocio.IFacadadeNegocio;
import constantes.Constantes;
import dominio.Cliente;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class PantallaClientes extends javax.swing.JDialog {
    private int ESPACIO_ENTRE_LINEAS = 40;
    private IFacadadeNegocio facadadeNegocio;
    private List<Cliente> listaDeClientes;
    private Calendar fechaActual;
    /**
     * Creates new form PantallaCitas
     * @param parent
     * @param modal
     * @param facadadeNegocio
     */
    public PantallaClientes(java.awt.Frame parent, boolean modal, IFacadadeNegocio facadadeNegocio) {
        super(parent, modal);
        initComponents();
        this.facadadeNegocio = facadadeNegocio;
        this.setLocationRelativeTo(null);
    }
    
    public void cargarClientes() {
        this.listaDeClientes = facadadeNegocio.obtenerClientes();
        String nombreColumnas [] = {"ID","Nombre","Apellido","Edad","Correo","Celular","Cliente Recomendador"};
        String cliente[][]= new String[this.listaDeClientes.size()][7];
        Cliente clienteAuxiliar;
        int saltosdeLinea = 1;
        for (int i = 0; i < this.listaDeClientes.size(); i++) {
            clienteAuxiliar = this.listaDeClientes.get(i);
            cliente[i][0] = Integer.toString(clienteAuxiliar.getIdCliente());
            cliente[i][1] = clienteAuxiliar.getNombre();
            cliente[i][2] = clienteAuxiliar.getApellido();
            cliente[i][3] = Integer.toString(clienteAuxiliar.getEdad());
            cliente[i][4] = clienteAuxiliar.getCorreo();
            cliente[i][5] = clienteAuxiliar.getCelular();
            if ((clienteAuxiliar.getIdClienteRecomendador())!=null) {
                cliente[i][6]= Integer.toString(clienteAuxiliar.getIdClienteRecomendador().getIdCliente());
            }else{
                cliente[i][6]= "";
            }
        }
        jTable_Cliente.setRowHeight(saltosdeLinea*this.ESPACIO_ENTRE_LINEAS);
        
        this.jTable_Cliente.setModel(new DefaultTableModel(cliente, nombreColumnas));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Cliente = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jPanel1 = new javax.swing.JPanel();
        jButton_AgregarCliente = new javax.swing.JButton();
        jButton_ModificarCita = new javax.swing.JButton();
        jButton_EliminarCita = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable_Cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "idCliente", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable_Cliente);

        jButton_AgregarCliente.setText("Agregar Cliente");
        jButton_AgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AgregarClienteActionPerformed(evt);
            }
        });

        jButton_ModificarCita.setText("Modificar Cliente");
        jButton_ModificarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ModificarCitaActionPerformed(evt);
            }
        });

        jButton_EliminarCita.setText("Eliminar Cliente");
        jButton_EliminarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EliminarCitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton_EliminarCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton_AgregarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_ModificarCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jButton_AgregarCliente)
                .addGap(18, 18, 18)
                .addComponent(jButton_ModificarCita)
                .addGap(18, 18, 18)
                .addComponent(jButton_EliminarCita)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AgregarClienteActionPerformed
        this.mostrarPantallaCliente(Constantes.AGREGAR, null);
    }//GEN-LAST:event_jButton_AgregarClienteActionPerformed

    private void jButton_ModificarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ModificarCitaActionPerformed
        this.mostrarPantallaCliente(Constantes.MODIFICAR, null);
    }//GEN-LAST:event_jButton_ModificarCitaActionPerformed

    private void jButton_EliminarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EliminarCitaActionPerformed
        this.mostrarPantallaCliente(Constantes.ELIMINAR, null);
    }//GEN-LAST:event_jButton_EliminarCitaActionPerformed

    public void mostrarPantallaCliente(int tipoDeOperacion, Cliente cliente) {
        PantallaCliente pantallaCliente = PantallaCliente.getInstancia(null, true, this.facadadeNegocio);
        this.setVisible(false);
        if(tipoDeOperacion == Constantes.AGREGAR) {
            pantallaCliente.mostrarPantalla(tipoDeOperacion, cliente);
        } else {
            int fila = this.jTable_Cliente.getSelectedRow();
            if (fila != -1) {
                Cliente clienteSeleccion = this.listaDeClientes.get(fila);
                pantallaCliente.mostrarPantalla(tipoDeOperacion, clienteSeleccion);
            } else {
                this.mostrarAdvertencia("Seleccione un cliente", JOptionPane.ERROR_MESSAGE);
            }
        }
        this.cargarClientes();
        this.setVisible(true);
    }
    
    public void mostrarAdvertencia(String mensaje, int tipoDeMensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Mensaje", tipoDeMensaje);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_AgregarCliente;
    private javax.swing.JButton jButton_EliminarCita;
    private javax.swing.JButton jButton_ModificarCita;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_Cliente;
    // End of variables declaration//GEN-END:variables
}
